[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "aws-cdk-lib>=2.202.0",
    "constructs>=10.4.2",
]
